import Foundation
import CoreData

@objc(Run)
public class Run: NSManagedObject {
    // This file will be automatically generated by Xcode
    // We're creating it manually for the purpose of this implementation
} 